export default interface IRepository {
  id: string;
  node_id: string;
  name: string;
  full_name: string;
  private: boolean;
  owner: {
    login: "takenet",
    id: 4369522,
    node_id: "MDEyOk9yZ2FuaXphdGlvbjQzNjk1MjI=",
    avatar_url: "https://avatars.githubusercontent.com/u/4369522?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/takenet",
    html_url: "https://github.com/takenet",
    followers_url: "https://api.github.com/users/takenet/followers",
    following_url: "https://api.github.com/users/takenet/following{/other_user}",
    gists_url: "https://api.github.com/users/takenet/gists{/gist_id}",
    starred_url: "https://api.github.com/users/takenet/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/takenet/subscriptions",
    organizations_url: "https://api.github.com/users/takenet/orgs",
    repos_url: "https://api.github.com/users/takenet/repos",
    events_url: "https://api.github.com/users/takenet/events{/privacy}",
    received_events_url: "https://api.github.com/users/takenet/received_events",
    type: "Organization",
    site_admin: false
  },
  html_url: string;
  description: string;
  fork: boolean;
  url: string;
  forks_url: string;
  keys_url: string;
  collaborators_url: string;
  teams_url: string;
  hooks_url: string;
  issue_events_url: string;
  events_url: string;
  assignees_url: string;
  branches_url: string;
  tags_url: string;
  blobs_url: string;
  git_tags_url: string;
  git_refs_url: string;
  trees_url: string;
  statuses_url: string;
  languages_url: string;
  stargazers_url: string;
  contributors_url: string;
  subscribers_url: string;
  subscription_url: string;
  commits_url: string;
  git_commits_url: string;
  comments_url: string;
  issue_comment_url: string;
  contents_url: string;
  compare_url: string;
  merges_url: string;
  archive_url: string;
  downloads_url: string;
  issues_url: string;
  pulls_url: string;
  milestones_url: string;
  notifications_url: string;
  labels_url: string;
  releases_url: string;
  deployments_url: string;
  created_at: "2021-02-09T11:47:43Z",
  updated_at: "2021-02-09T17:19:30Z",
  pushed_at: "2021-02-09T17:19:27Z",
  git_url: string;
  ssh_url: string;
  clone_url: string;
  svn_url: string;
  homepage: null;
  size: string;
  stargazers_count: string;
  watchers_count: string;
  language: null,
  has_issues: true,
  has_projects: true,
  has_downloads: true,
  has_wiki: true,
  has_pages: false,
  forks_count: string;
  mirror_url: null,
  archived: false,
  disabled: false,
  open_issues_count: string;
  license: null,
  allow_forking: true,
  is_template: false,
  web_commit_signoff_required: false,
  topics: string[];
  visibility: string;
  forks: string;
  open_issues: string;
  watchers: string;
  default_branch: string;
}